project					= "myfirstproject-298711"
region					= "us-central1"
zone					= "us-central1-c"
instance_name	        = "test-instance-dns"
machine_type			= "f1-micro"
image			        = "debian-cloud/debian-9"
dns_managed_zone		= "prod-zone"
dns_name		        = "prod.mydomain.com."